# Generated by Django 4.2.5 on 2023-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='garage',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
