# Generated by Django 4.2.5 on 2023-10-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubdate',
            field=models.DateField(auto_now=True),
        ),
    ]
